adot-collector:
  image: public.ecr.aws/aws-observability/aws-otel-collector:v0.43.3
  command: ["--config", "/etc/otel-agent-config.yaml"]
  environment:
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - AWS_REGION=${AWS_REGION:-us-east-1}
    - OTEL_SERVICE_NAME=shopiet-adot-collector
    - OTEL_SERVICE_VERSION=1.0.0
    - ENVIRONMENT=${ENVIRONMENT:-development}
  volumes:
    - ./adot-collector-config.yaml:/etc/otel-agent-config.yaml:ro
    - /tmp/otelcol-filestore:/tmp/otelcol-filestore
  ports:
    - "4317:4317"   # OTLP gRPC
    - "4318:4318"   # OTLP HTTP  
    - "13133:13133" # Health check
    - "1777:1777"   # pprof
    - "55679:55679" # zpages
    - "8888:8888"   # Internal metrics
  depends_on:
    - db
    - redis
  networks:
    - shopiet-network
  restart: unless-stopped
