version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: shopiet_db
      POSTGRES_USER: shopiet_user
      POSTGRES_PASSWORD: shopiet_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shopiet_user -d shopiet_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./Backend(Docked)
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./Backend(Docked):/app
      - ~/.config/gcloud/application_default_credentials.json:/app/gcp_credentials.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp_credentials.json
      - POSTGRES_DB=shopiet_db
      - POSTGRES_USER=shopiet_user
      - POSTGRES_PASSWORD=shopiet_password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_URL=redis://redis:6379
      - DJANGO_SETTINGS_MODULE=backend.settings
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: 
      context: ./Frontend
      dockerfile: Dockerfile
    command: npm run dev
    working_dir: /app
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:

networks:
  default:
    name: shopiet-network