version: '3.8'
 
services:
  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: on-failure
 
  backend:
    build: ./server
    environment:
      - MONGO_URL=mongodb://mongo:27017/shopiet
      - PORT=5000
    depends_on:
      - mongo
    restart: on-failure
 
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
 
volumes:
  mongo-data:
