# Logstash Configuration for Shopiet Application
http.host: "0.0.0.0"
http.port: 9600

# Path settings
path.config: /usr/share/logstash/pipeline
path.data: /usr/share/logstash/data
path.logs: /usr/share/logstash/logs

# Pipeline settings
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# Monitoring
monitoring.enabled: false
config.reload.automatic: true
config.reload.interval: 3s

# JVM settings
log.level: info
