# Generated by Django 5.0 on 2024-04-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_thumbnail', models.ImageField(upload_to='article_thumbnails')),
                ('item_description', models.TextField()),
                ('slug', models.SlugField(default='djangodbmodelsfieldscharfield', max_length=255, unique=True)),
                ('time_stamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
