# Generated by Django 5.0 on 2024-04-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopiet', '0004_item_item_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
