# Generated by Django 5.0 on 2024-04-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopiet', '0007_item_item_category_name_item_item_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='m_description',
            field=models.TextField(blank=True),
        ),
    ]
