# Generated by Django 5.0 on 2024-05-05 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopiet', '0010_alter_item_item_condition_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user',
        ),
    ]
