# Generated by Django 5.0 on 2024-05-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopiet', '0014_alter_profile_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
