# Generated by Django 5.0 on 2024-05-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopiet', '0015_item_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='address',
        ),
        migrations.AddField(
            model_name='item',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='latitude',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='longitude',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
