# Generated by Django 5.0 on 2024-05-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopiet', '0015_item_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
