# Generated by Django 5.0 on 2024-05-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopiet', '0016_item_latitude_item_longitude'),
        ('shopiet', '0016_remove_item_address_item_delivery_item_latitude_and_more'),
    ]

    operations = [
    ]
