# Generated by Django 5.0 on 2024-05-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopiet', '0017_merge_20240527_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='latitude',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='longitude',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
