# Generated by Django 5.0 on 2024-06-11 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopiet', '0020_chats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chats',
        ),
    ]
