# Generated by Django 5.0 on 2025-07-28 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopiet', '0024_alter_item_item_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='latitudes',
        ),
    ]
