# Generated by Django 5.0 on 2024-04-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopiet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_thumbnail',
            field=models.ImageField(upload_to='item_thumbnails'),
        ),
    ]
